name: Merge new translations to .desktop and NSIS

on:
  push:
    branches:
      - master
    paths:
      - 'po/*.po' # translation changed

permissions:
  contents: read

jobs:
  update-desktop:
    if: github.repository == 'bleachbit/bleachbit'
    runs-on: ubuntu-latest
    permissions:
      contents: write # commit and push localization files

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make wget gettext
          wget https://raw.githubusercontent.com/bleachbit/bleachbit-misc/refs/heads/master/extract_desktop.py
          python3 -m pip install --upgrade pip setuptools

      - name: Compile message catalogs to binary format
        run: make -C po local

      - name: Extract translations from .mo to .desktop
        run: python3 extract_desktop.py

      # Generate NsisInclude/BleachBitLang.nsh from po/*.po
      - name: Extract translations to NSIS
        run: python3 windows/nsis_translations.py --generate

      - name: Commit if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add org.bleachbit.BleachBit.desktop windows/NsisInclude/NsisMultiUserLang.nsh
          if git diff --cached --quiet; then
              echo "No changes to commit."
          else
              git commit -m 'Update localization files' -m 'Automatically extracted from ./po/*.po'
              git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" "HEAD:${{ github.ref_name }}"
          fi
