name: zizmor

on:
  push:
    branches:
      - '**'
      - '!dependabot/**' # avoid duplicate runs; the pull_request event handles dependabot PRs
    paths:
      - '.github/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/**'
  schedule:
    - cron: '30 5 * * 1'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  zizmor:
    name: Run zizmor
    # The zimzore action requires working Docker daemon, which is not provided on ubuntu-slim.
    # The zimzor binary could be installed directly on -slim, but it is simpler to use
    # ubuntu-latest.
    runs-on: ubuntu-latest
    # Normal runtime is under 30 seconds.
    timeout-minutes: 5

    permissions:
      security-events: write # upload SARIF to code scanning
      contents: read
      actions: read

    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
