import six
from typing import Union, overload

str_or_bytes = Union[six.text_type, six.binary_type]

def expandvars(var: six.text_type) -> six.text_type: ...
def expanduser(path: six.text_type) -> six.text_type: ...
def decode_str(s: str_or_bytes) -> six.text_type: ...
def ensure_unicode(s: str_or_bytes) -> six.text_type: ...
def fsdecode(filename: str_or_bytes) -> six.text_type: ...
def fsencode(filename: str_or_bytes) -> six.binary_type: ...

