import six
from typing import Union

def expandvars(var: six.text_type) -> six.text_type: ...
def expanduser(path: six.text_type) -> six.text_type: ...
def decode_str(s: Union[six.binary_type,six.text_type]) -> six.text_type: ...
def ensure_unicode(s: Union[six.binary_type,six.text_type]) -> six.text_type: ...
